pr: none
trigger: none

pool:
  vmImage: ubuntu-20.04

variables:
  buildVersion: 0.0.0

steps:
- checkout: self
  fetchDepth: 0

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- bash: |
    version=14.0.0-alpha-$(git rev-list --count $BUILD_SOURCEVERSION)
    echo 'New version='$version
    echo "##vso[task.setvariable variable=buildVersion;]$version"
  displayName: Set version

- bash: |
    echo '##vso[build.updatebuildnumber]$(buildVersion)'
  displayName: Set build name

- bash: |
    git config --global user.email "syampolsky@finitive.com"
    git config --global user.name "Steven Yampolsky"
    npm version $(buildVersion)
  displayName: npm version

- bash: |
    yarn install --frozen-lockfile
  displayName: npm install

- bash: |
    npm run build:npm
  displayName: npm build

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc
  displayName: npm authenticate


- task: Npm@1
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: Finitive/npmjs
  displayName: Publish