pr: none
trigger:
    branches:
        include:
            - develop
    paths:
        exclude:
            - .azure/*

pool:
    vmImage: ubuntu-20.04

jobs:
    - job: Test
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: '12.x'
            displayName: Set Node version
          - task: YarnInstaller@3
            inputs:
                versionSpec: '1.x'
            displayName: Set Yarn Version

          - publish: $(System.DefaultWorkingDirectory)
            name: source
            artifact: src

          - script: |
                yarn install --frozen-lockfile
                yarn pretest
                yarn build
            displayName: Run Test

          - task: PublishTestResults@2
            inputs:
                testResultsFormat: 'JUnit'
                testResultsFiles: 'junit.xml'

          - task: PublishCodeCoverageResults@1
            inputs:
                codeCoverageTool: 'Cobertura'
                summaryFileLocation: 'coverage/cobertura-coverage.xml'
