pr: none
trigger: none

pool:
    vmImage: ubuntu-20.04

steps:
    - script: |
        mv package.json package.orig
        sed "s/\"0.0.0-semantically-released\"/\"14.0.0-finitive-$(Rev:rr)\"/g" package.orig > package.json
    - script: |
        yarn install --non-interactive --frozen-lockfile --cache-folder ~/.cache/yarn
    - script: |
        yarn clean
    - script: |
        yarn build:i18n
    - script: |
        yarn build:ci:es
    - script: |
        yarn build:ci:dist
    - script: |
        tarn test

    - publish: $(System.DefaultWorkingDirectory)
      name: source
      artifact: src

    - task: Npm@1
      inputs:
        command: 'publish'
        publishRegistry: 'useFeed'
        publishFeed: '80bd0842-15be-4bac-8442-82eada5ce15f/4424f450-4ea4-4d30-ab33-6a067ed3327c'

    # - task: PublishTestResults@2
    #   inputs:
    #       testResultsFormat: 'JUnit'
    #       testResultsFiles: 'junit.xml'

    # - task: PublishCodeCoverageResults@1
    #   inputs:
    #       codeCoverageTool: 'Cobertura'
    #       summaryFileLocation: 'coverage/cobertura-coverage.xml'
